FROM ubuntu

COPY web/envoy.yaml /etc/envoy.yaml

RUN apt update
RUN apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
RUN curl -sL 'https://getenvoy.io/gpg' | apt-key add -
 # verify the key
RUN apt-key fingerprint 6FF974DB | grep "5270 CEAC"
RUN add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"
RUN apt update
RUN apt install -y getenvoy-envoy
RUN apt install -y telnet

CMD /usr/bin/envoy -c /etc/envoy.yaml -l trace --log-path /tmp/envoy_info.log
